name: Run stocks.py Daily

on:
  schedule:
    # Runs at 10:00 AM every day (Cron format: minute hour * * *, wildcard in the day, month year posn means it runs every day etc)
    - cron: '0 10 * * *'

  workflow_dispatch: # Allows manual trigger if needed

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repo
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Specify your Python version

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run the Python script
    - name: Run stocks.py
      run: python stocks.py
