name: Run weather.sh Daily

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest #Specify to use a Ubuntu virtual machine

    steps:
    - name: Checkout Repo #Clone the repository onto the virtual machine
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' 

    - name: Install Dependencies #This step not required for bash script, requirements.txt is empty. 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run weather.sh
      run: ./weather.sh

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Commit and Push Changes
      run: |
        git add -A
        git commit -m "Daily auto-run of weather.sh" || echo "No changes to commit"
        git push

      env:
        # Set this secret in your GitHub repository settings under "Secrets and variables" -> "Actions"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}