name: Run weather.sh Daily

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-22.04 #Ubuntu latest switched back to ubuntu 22 on Dec 5th see https://github.com/actions/runner-images/issues/10636

    steps:
    - name: Checkout Repo #Clone the repository onto the virtual machine
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' 

    - name: Run weather.sh
      run: ./weather.sh

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
  
    - name: Set Commit Message
      id: set-message
      run: |
        if [[ "${{ github.event_name }}" == "schedule" ]]; then
          echo "commit_message=Scheduled daily auto-run of weather.sh" >> $GITHUB_ENV
        elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "commit_message=Manual run of weather.sh workflow" >> $GITHUB_ENV
        fi

    - name: Commit and Push Changes
      run: |
        git add -A
        git commit -m "$COMMIT_MESSAGE" || echo "No changes to commit"
        git push

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}